apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.acme_email }}
    privateKeySecretRef:
      name: letsencrypt-staging-dns01-key-pair
    solvers:
    - dns01:
        route53:
          region: {{ .Values.route53_region }}
          hostedZoneID: {{ .Values.route53_zone_id }}
