# https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
# https://github.com/grafana/loki/blob/main/docs/sources/setup/install/helm/install-scalable/_index.md

deploymentMode: SimpleScalable
loki:
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4

  storage:
    type: s3

    # TF
    # bucketNames:
    #   chunks: "chunks"
    #   ruler: "ruler"
    #   admin: "admin"

    s3:
      # X
      # # s3 URL can be used to specify the endpoint, access key, secret key, and bucket name
      # s3: s3://access_key:secret_access_key@custom_endpoint/bucket_name

      # TF
      # # AWS endpoint URL
      # endpoint: <your-endpoint>

      # TF
      # # AWS region where the S3 bucket is located
      # region: <your-region>

      # TF
      # # AWS secret access key
      # secretAccessKey: <your-secret-access-key>

      # TF
      # # AWS access key ID
      # accessKeyId: <your-access-key-id>

      # TODO ???
      # AWS signature version (e.g., v2 or v4)
      # signatureVersion: <your-signature-version>
      signatureVersion: v4
      # https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

      # Forces the path style for S3 (true/false)
      s3ForcePathStyle: false

      # Allows insecure (HTTP) connections (true/false)
      insecure: false

      # TODO ???
      # HTTP configuration settings
      http_config: {}

# TODO ???
#gateway:
#  ingress:
#    enabled: true
#    hosts:
#      - host: FIXME
#        paths:
#          - path: /
#            pathType: Prefix

backend:
  replicas: 3
read:
  replicas: 3
write:
  replicas: 3

# Disable minio for storage
minio:
  enabled: false

# Zero out replica counts of other deployment modes
singleBinary:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
