# Ref: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#ssl-passthrough

# Note: The tls: true option will expect that the argocd-server-tls secret exists as Argo CD server loads TLS certificates from this place.

# OVERRIDE
# global:
#   domain: argocd.example.com

certificate:
  enabled: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls: true
