# Ref: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#ssl-termination-at-ingress-controller

# OVERRIDE
# global:
#   domain: argocd.example.com

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

    # OVERRIDE
    # extraTls:
    #   - hosts:
    #     - argocd.example.com

    extraTls:
      # Based on the ingress controller used secret might be optional
      - secretName: wildcard-tls
