version: '3.1'

services:

  mongo:
    image: mongo:7.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: default

  crud-api:
    build:
      context: ./crud-api
    ports:
      - 8080:8080
      - 9100:9100
    environment:
      LOG_LEVEL: INFO
      MONGO_URI: mongodb://root:example@mongo:27017
      MONGO_DATABASE: default

  crud-client:
    build:
      context: ./crud-client
    environment:
      LOG_LEVEL: INFO
      API_URL: http://crud-api:8080/api/items
      MIN_ITERATIONS: 1
      MAX_ITERATIONS: 10
      POST_WEIGHT: 0.25
      GET_WEIGHT: 0.25
      PUT_WEIGHT: 0.25
      DELETE_WEIGHT: 0.25
      INVALID_INPUT_CHANCE: 0.1
    restart: always
