name: x) Apply Cert-Manager

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cert-manager/**'

jobs:
  cert-manager:
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: cert-manager
    secrets: inherit
