on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'namespace-governance/**'

jobs:
  namespace-governance:
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: namespace-governance
    secrets: inherit
