name: x) Apply Ingress-Nginx

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ingress-nginx/**'

jobs:
  ingress-nginx:
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: ingress-nginx
    secrets: inherit
