name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:

  vpc-network:
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: vpc-network
    secrets: inherit

  eks-cluster:
    needs: [vpc-network]
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: eks-cluster
    secrets: inherit

  namespace-governance:
    needs: [eks-cluster]
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: namespace-governance
    secrets: inherit

  crds:
    needs: [eks-cluster]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          role-session-name: crds # TODO add a more descriptive name? include owner? repo? workflow name?
          aws-region: ${{ vars.AWS_REGION }}
      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }}
      - name: Apply CRDs
        run: |
          kubectl version
          kubectl config current-context
          kubectl apply --server-side -k crds/

  ingress-nginx:
    needs: [namespace-governance]
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: ingress-nginx
    secrets: inherit

# # route53-dns
# cert-manager
# kube-prometheus-stack
# argo-cd
# hello-world
# # argocd-applications

# # TODO need to wait until all certificates are issued
# # tls-secrets-backup
