name: Deploy Component

on:
  workflow_dispatch:
    inputs:
      component:
        description: Component to deploy
        type: string
        required: true
        options:
          - vpc-network
          - eks-cluster
          - namespace-governance
          - crds
          - ingress-nginx
          - kube-prometheus-stack
          - cert-manager
          - argo-cd
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      argo-cd: ${{ steps.filter.outputs.argo-cd }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            # vpc-network:
            #   - 'vpc-network/**'
            # argo-cd:
            #   - 'argo-cd/**'
            vpc-network: ['vpc-network/**']
            eks-cluster: ['eks-cluster/**']
            namespace-governance: ['namespace-governance/**']
            crds: ['crds/**']
            ingress-nginx: ['ingress-nginx/**']
            kube-prometheus-stack: ['kube-prometheus-stack/**']
            cert-manager: ['cert-manager/**']
            argo-cd: ['argo-cd/**']

  vpc-network:
    needs: [changes]
    if: (github.event_name == 'workflow_dispatch' && inputs.component == 'vpc-network') || (github.event_name == 'push' && needs.changes.outputs.vpc-network == 'true')
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: vpc-network
    secrets: inherit

  eks-cluster:
    needs: [changes]
    if: (github.event_name == 'workflow_dispatch' && inputs.component == 'eks-cluster') || (github.event_name == 'push' && needs.changes.outputs.eks-cluster == 'true')
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: eks-cluster
    secrets: inherit

  namespace-governance:
    needs: [changes]
    if: (github.event_name == 'workflow_dispatch' && inputs.component == 'namespace-governance') || (github.event_name == 'push' && needs.changes.outputs.namespace-governance == 'true')
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: namespace-governance
    secrets: inherit

  crds:
    needs: [changes]
    if: (github.event_name == 'workflow_dispatch' && inputs.component == 'crds') || (github.event_name == 'push' && needs.changes.outputs.crds == 'true')
    uses: ./.github/workflows/kubectl-apply.yaml
    with:
      path: crds/
      kustomize: true
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  ingress-nginx:
    needs: [changes]
    if: (github.event_name == 'workflow_dispatch' && inputs.component == 'ingress-nginx') || (github.event_name == 'push' && needs.changes.outputs.ingress-nginx == 'true')
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: ingress-nginx
    secrets: inherit

  kube-prometheus-stack:
    needs: [changes]
    if: (github.event_name == 'workflow_dispatch' && inputs.component == 'kube-prometheus-stack') || (github.event_name == 'push' && needs.changes.outputs.kube-prometheus-stack == 'true')
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: kube-prometheus-stack
    secrets: inherit

  cert-manager:
    needs: [changes]
    if: (github.event_name == 'workflow_dispatch' && inputs.component == 'cert-manager') || (github.event_name == 'push' && needs.changes.outputs.cert-manager == 'true')
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: cert-manager
    secrets: inherit

  argo-cd:
    needs: [changes]
    if: (github.event_name == 'workflow_dispatch' && inputs.component == 'argo-cd') || (github.event_name == 'push' && needs.changes.outputs.argo-cd == 'true')
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: argo-cd
    secrets: inherit
