name: Deploy

on:
  workflow_dispatch:

jobs:

  vpc-network:
    uses: .github/workflows/terraform-apply.yaml@main
    with:
      dir: vpc-network

  eks-cluster:
    needs: [vpc-network]
    uses: .github/workflows/terraform-apply.yaml@main
    with:
      dir: eks-cluster
