name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:

  vpc-network:
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: vpc-network
    secrets: inherit

  eks-cluster:
    needs: [vpc-network]
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: eks-cluster
    secrets: inherit

  namespace-governance:
    needs: [eks-cluster]
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: namespace-governance
    secrets: inherit

  crds:
    needs: [eks-cluster]
    uses: ./.github/workflows/kubectl-apply.yaml
    with:
      path: crds/
      kustomize: true
    secrets: inherit

  ingress-nginx:
    needs: [namespace-governance]
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: ingress-nginx
    secrets: inherit

  kube-prometheus-stack:
    needs: [namespace-governance, crds]
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: kube-prometheus-stack
    secrets: inherit

  cert-manager:
    needs: [namespace-governance, crds]
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: cert-manager
    secrets: inherit

  argo-cd:
    needs: [namespace-governance, crds]
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: argo-cd
    secrets: inherit
