name: Deploy

on:
  workflow_dispatch:

jobs:
  vpc-network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add terraform-config.env
        run: echo "${{ vars.TERRAFORM_CONFIG_ENV }}" > terraform-config.env
      - name: Run terraform-config.sh
        run: ./terraform-config.sh --dir vpc-network --no-prompt
      - name: Terraform init
        run: |
          if [ -f vpc-network/terraform.cloud.env ]; then
            source vpc-network/terraform.cloud.env
          fi
          terraform -chdir=vpc-network init
      - name: Terraform apply
        run: |
          if [ -f vpc-network/terraform.cloud.env ]; then
            source vpc-network/terraform.cloud.env
          fi
          terraform -chdir=vpc-network apply -auto-approve
