name: Deploy Component

on:
  workflow_dispatch:
    inputs:
      component:
        description: Component to deploy
        type: string
        required: true
        options:
          - vpc-network
          - argo-cd
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      argo-cd: ${{ steps.filter.outputs.argo-cd }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            vpc-network:
              - 'vpc-network/**'
            argo-cd:
              - 'argo-cd/**'

  vpc-network:
    needs: [changes]
    if: (github.event_name == 'workflow_dispatch' && inputs.component == 'vpc-network') || (github.event_name == 'push' && needs.changes.outputs.vpc-network == 'true')
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: vpc-network
    secrets: inherit

  argo-cd:
    needs: [changes]
    if: (github.event_name == 'workflow_dispatch' && inputs.component == 'argo-cd') || (github.event_name == 'push' && needs.changes.outputs.argo-cd == 'true')
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      dir: argo-cd
    secrets: inherit
