on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['terraform-backend/**']

jobs:
  terraform-backend:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace placeholders
        run: |
          eval "$(echo '${{ vars.PLACEHOLDERS_JSON }}' | jq -r 'to_entries[] | "find . -type f -exec sed -i \"s/\(.key)/\(.value)/g\" {} +"')"
          if grep -rP '__[A-Z_]+__' .; then echo "Not all placeholders have been replaced"; exit 1; fi

      - name: AWS configure
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: AWS CloudFormation deploy
        working-directory: terraform-backend
        run: |
          source config.env
          aws cloudformation deploy \
          --region $AWS_REGION \
          --stack-name $CLOUDFORMATION_STACK_NAME \
          --template-file cloudformation-template.yaml \
          --tags IaCRepository=$IAC_REPOSITORY \
          --parameter-overrides \
              S3BucketName=$S3_BUCKET_NAME \
              DynamoDBTableName=$DYNAMODB_TABLE_NAME \
              IaCRepository=$IAC_REPOSITORY
