name: Terraform Apply

on:
  workflow_call:
    inputs:
      dir:
        type: string
        required: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"
          cli_config_credentials_token: "${{ secrets.TFE_TOKEN }}"
      - name: Terraform Init
        run: |
          export TF_CLOUD_ORGANIZATION="${{ vars.TF_CLOUD_ORGANIZATION }}"
          export TF_CLOUD_PROJECT="${{ vars.TF_CLOUD_PROJECT }}"
          export TF_WORKSPACE="${{ vars.TF_CLOUD_PROJECT }}-${{ inputs.dir }}"
          terraform -chdir=${{ inputs.dir }} init
      - name: Terraform Apply
        run: |
          export TF_CLOUD_ORGANIZATION="${{ vars.TF_CLOUD_ORGANIZATION }}"
          export TF_CLOUD_PROJECT="${{ vars.TF_CLOUD_PROJECT }}"
          export TF_WORKSPACE="${{ vars.TF_CLOUD_PROJECT }}-${{ inputs.dir }}"
          terraform -chdir=${{ inputs.dir }} apply -input=false -auto-approve
