name: Terraform plan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  vpc-network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"
          cli_config_credentials_token: "${{ secrets.TFE_TOKEN }}"
      - name: Terraform init
        run: |
          export TF_CLOUD_ORGANIZATION="${{ vars.TF_CLOUD_ORGANIZATION }}"
          export TF_CLOUD_PROJECT="${{ vars.TF_CLOUD_PROJECT }}"
          export TF_WORKSPACE="${{ vars.TF_CLOUD_PROJECT }}-vpc-network"
          terraform -chdir=vpc-network init
      - name: Terraform plan
        run: |
          export TF_CLOUD_ORGANIZATION="${{ vars.TF_CLOUD_ORGANIZATION }}"
          export TF_CLOUD_PROJECT="${{ vars.TF_CLOUD_PROJECT }}"
          export TF_WORKSPACE="${{ vars.TF_CLOUD_PROJECT }}-vpc-network"
          terraform -chdir=vpc-network plan -input=false -compact-warnings
